<a href="https://colab.research.google.com/github/AndreaBravo52/AlgoritmosGeneticos/blob/main/algoritmo_genetico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy
# Implements the random initialization of individuals using the binary representation.
def createIndividual(nbBits):
  individuo=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  individuo[0:5]=numpy.random.randint(15, size = nbBits)
  individuo[5:10]=numpy.random.randint(19, size = nbBits)
  individuo[10:15]=numpy.random.randint(16, size = nbBits)
  return individuo
# Implements the one point crossover on individuals using the binary representation.
def combine(parentA, parentB, cRate):
  if (random.random() <= cRate):
    cPoint = numpy.random.randint(1, len(parentA))
    offspringA = numpy.append(parentA[0:cPoint], parentB[cPoint:])
    offspringB = numpy.append(parentB[0:cPoint], parentA[cPoint:])
  else:
    offspringA = numpy.copy(parentA)
    offspringB = numpy.copy(parentB)
  return offspringA, offspringB
# Implements the flip mutation on individuals using the binary representation.
def mutate(individual, mRate):
  for i in range(len(individual)):
    if (random.random() <= mRate):
      if (individual[i] >= 1):
        individual[i] = 0
      else:
        individual[i] = individual[i]
  return individual
# Implements the fitness function of individuals using the binary representation and solving the max-one problem.
def evaluate(individual):
  x = 0
  y = 0
  cf=[5,10,8]
  #subir costo si entregas mas de lo que tienes
  if (sum(individual[0:5])>20):
    x = x + 500
  if (sum(individual[5:10])>30):
    x = x + 500
  if (sum(individual[10:15])>25):
    x = x + 500
  # Suma costos de apertura
  if (sum(individual[0:5])>0):
    y = y + cf[0]
  if (sum(individual[6:10])>0):
    y = y + cf[1]
  if (sum(individual[11:15])>0):
    y = y + cf[2]
  #subir costos si entregas menos de los que se pide
  if(individual[0]+individual[5]+individual[10]<10):
    x=x+500
  if(individual[1]+individual[6]+individual[11]<8):
    x=x+500
  if(individual[2]+individual[7]+individual[12]<15):
    x=x+500
  if(individual[3]+individual[8]+individual[13]<7):
    x=x+500
  if(individual[4]+individual[9]+individual[14]<12):
    x=x+500
  costo=[2,3,4,5,7,4,3,1,2,6,5,4,2,1,3]
  z=0
  i=0
  for i in range(len(individual)):
    z=costo[i]*individual[i]
  return x+z+y
# Implements the tournament selection.
def select(population, evaluation, tournamentSize):
  winner = numpy.random.randint(0, len(population))
  for i in range(tournamentSize - 1):
    rival = numpy.random.randint(0, len(population))
    if (evaluation[rival] > evaluation[winner]):
      winner = rival
  return population[winner]
# Implements a genetic algorithm for solving the max-one problem with individuals using the binary representation.
def geneticAlgorithm(n, populationSize, cRate, mRate, generations):
  # Creates the initial population (it also evaluates it)
  population = [None] * populationSize
  evaluation = [None] * populationSize
  for i in range(populationSize):
    individual = createIndividual(n)
    population[i] = individual
    evaluation[i] = evaluate(individual)
  # Keeps a record of the best individual found so far
  index = 0;
  for i in range(1, populationSize):
    if (evaluation[i] < evaluation[index]):
      index = i;
  bestIndividual = population[index]
  bestEvaluation = evaluation[index]
  # Runs the evolutionary process
  for i in range(generations):
    k = 0
    newPopulation = [None] * populationSize
    for j in range(populationSize // 2):
      parentA = select(population, evaluation, 3)
      parentB = select(population, evaluation, 3)
      newPopulation[k], newPopulation[k + 1] = combine(parentA, parentB, cRate)
      k = k + 2
    population = newPopulation
    for j in range(populationSize):
      population[j] = mutate(population[j], mRate)
      evaluation[j] = evaluate(population[j])
      # Keeps a record of the best individual found so far
      if (evaluation[j] > bestEvaluation):
        bestEvaluation = evaluation[j]
        bestIndividual = population[j]
  return bestIndividual, bestEvaluation
# solves the problem using the genetic algorithm
solution, evaluation = geneticAlgorithm(5, 200, 0.9, 0.5, 1000)
print(solution)
print(evaluation)

[ 9  0 11  2  0  0  0  0  0  2  0  0  0  0  8]
3047


In [ ]:
#Prueba de nuevo combine con creacion de individuos 2
import random
import numpy
def suma_exacta(n, total):
    dividers = sorted(random.sample(range(1,total),n-1))
    return [a - b for a, b in zip(dividers + [total],[0] + dividers)]

# Implements the random initialization of individuals using the binary representation.
def createIndividual(nbBits):
  individuo=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  individuo[0:5]=suma_exacta(5, 30)
  individuo[5:10]=suma_exacta(5, 20)
  individuo[10:15]=suma_exacta(5, 25)
  return individuo
# Implements the one point crossover on individuals using the binary representation.
def combine(parentA, parentB, cRate):
  if (random.random() <= cRate):
    cPoint = numpy.random.randint(1, len(parentA))
    z=parentA[0:cPoint]
    random.shuffle(z)
    w=parentB[cPoint:]
    random.shuffle(w)
    offspringA = numpy.append(z, w)
    z=parentA[cPoint:]
    random.shuffle(z)
    w=parentB[0:cPoint]
    random.shuffle(w)
    offspringB = numpy.append(w, z)
  else:
    offspringA = numpy.copy(parentA)
    offspringB = numpy.copy(parentB)
  return offspringA, offspringB
# Implements the flip mutation on individuals using the binary representation.
def mutate(individual, mRate):
  for i in range(len(individual)):
    if (random.random() <= mRate):
      if (individual[i] >= 1): #si esta entregando que deje de entregar
        individual[i] = 0
      else:
        nuevoInt = numpy.random.randint(1, 12)
        individual[i] = individual[i]+  nuevoInt#si no esta entregando que agrega una cantidad aleatoria
  return individual
# Implements the fitness function of individuals using the binary representation and solving the max-one problem.
def evaluate(individual):
  x = 0
  y = 0
  cf=[5,10,8]
  #subir costo si entregas mas de lo que tienes
  if (sum(individual[0:5])>20):
    x = x + 500
  if (sum(individual[5:10])>30):
    x = x + 500
  if (sum(individual[10:15])>25):
    x = x + 500
  # Suma costos de apertura
  if (sum(individual[0:5])>0):
    y = y + cf[0]
  if (sum(individual[6:10])>0):
    y = y + cf[1]
  if (sum(individual[11:15])>0):
    y = y + cf[2]
  #subir costos si entregas menos de los que se pide
  if(individual[0]+individual[5]+individual[10]<10):
    x=x+500
  if(individual[1]+individual[6]+individual[11]<8):
    x=x+500
  if(individual[2]+individual[7]+individual[12]<15):
    x=x+500
  if(individual[3]+individual[8]+individual[13]<7):
    x=x+500
  if(individual[4]+individual[9]+individual[14]<12):
    x=x+500
  costo=[2,3,4,5,7,4,3,1,2,6,5,4,2,1,3]
  z=0
  i=0
  for i in range(len(individual)):
    z=z+costo[i]*individual[i]
  costoTot=x+y+z
  return costoTot
# Implements the tournament selection.
def select(population, evaluation, tournamentSize):
  winner = numpy.random.randint(0, len(population))
  for i in range(tournamentSize - 1):
    rival = numpy.random.randint(0, len(population))
    if (evaluation[rival] < evaluation[winner]):
      winner = rival
  return population[winner]
# Implements a genetic algorithm for solving the max-one problem with individuals using the binary representation.
def geneticAlgorithm(n, populationSize, cRate, mRate, generations):
  # Creates the initial population (it also evaluates it)
  population = [None] * populationSize
  evaluation = [None] * populationSize
  for i in range(populationSize):
    individual = createIndividual(n)
    population[i] = individual
    evaluation[i] = evaluate(individual)
  # Keeps a record of the best individual found so far
  index = 0;
  for i in range(1, populationSize):
    if (evaluation[i] < evaluation[index]):
      index = i;
  bestIndividual = population[index]
  bestEvaluation = evaluation[index]
  # Runs the evolutionary process
  for i in range(generations):
    k = 0
    newPopulation = [None] * populationSize
    for j in range(populationSize // 2):
      parentA = select(population, evaluation, 3)
      parentB = select(population, evaluation, 3)
      newPopulation[k], newPopulation[k + 1] = combine(parentA, parentB, cRate)
      k = k + 2
    population = newPopulation
    for j in range(populationSize):
      population[j] = mutate(population[j], mRate)
      evaluation[j] = evaluate(population[j])
      # Keeps a record of the best individual found so far
      if (evaluation[j] < bestEvaluation):
        bestEvaluation = evaluation[j]
        bestIndividual = population[j]
  return bestIndividual, bestEvaluation
# solves the problem using the genetic algorithm
solution, evaluation = geneticAlgorithm(5, 20, 0.9, 0.1, 1000)
print(solution)
print(evaluation)

[10  6  0  4  0  7  0  5  6  0  6  0  4  7  7]
198


In [ ]:
#EXPERIMENTO LALO (SALE CASI IGUAL AL DE ARRIBA :P)
import random
import numpy

import random
def suma_exacta(n, total):
    dividers = sorted(random.sample(range(1,total),n-1))
    return [a - b for a, b in zip(dividers + [total],[0] + dividers)]

# Implements the random initialization of individuals using the binary representation.
def createIndividual(nbBits):
  individuo=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  individuo[0:5]=suma_exacta(5, 20)
  individuo[5:10]=suma_exacta(5, 30)
  individuo[10:15]=suma_exacta(5, 25)
  return individuo
# Implements the one point crossover on individuals using the binary representation.
def combine(parentA, parentB, cRate):
  if (random.random() <= cRate):
    cPoint = numpy.random.randint(1, len(parentA))
    offspringA = numpy.append(parentA[0:cPoint], parentB[cPoint:])
    offspringB = numpy.append(parentB[0:cPoint], parentA[cPoint:])
  else:
    offspringA = numpy.copy(parentA)
    offspringB = numpy.copy(parentB)
  return offspringA, offspringB
# Implements the flip mutation on individuals using the binary representation.
def mutate(individual, mRate):
  for i in range(len(individual)):
    if (random.random() <= mRate):
      if (individual[i] == 0):
        individual[i] = 1
      else:
        individual[i] = 0
  return individual
# Implements the fitness function of individuals using the binary representation and solving the max-one problem.
def evaluate(individual):
  x = 0
  y = 0
  cf=[5,10,8]
  if (sum(individual[0:5])>20):
    x = x + 500
  if (sum(individual[5:10])>30):
    x = x + 500
  if (sum(individual[10:15])>25):
    x = x + 500
  # Suma costos de apertura
  if (sum(individual[0:5])>0):
    y = y + cf[0]
  if (sum(individual[6:10])>0):
    y = y + cf[1]
  if (sum(individual[11:15])>0):
    y = y + cf[2]
  if(individual[0]+individual[5]+individual[10]<10):
    x=x+500
  if(individual[1]+individual[6]+individual[11]<8):
    x=x+500
  if(individual[2]+individual[7]+individual[12]<15):
    x=x+500
  if(individual[3]+individual[8]+individual[13]<7):
    x=x+500
  if(individual[4]+individual[9]+individual[14]<12):
    x=x+500
  costo=[2,3,4,5,7,4,3,1,2,6,5,4,2,1,3]
  z=0
  i=0
  for i in range(len(individual)):
    z=costo[i]*individual[i]
  return x+z+y
# Implements the tournament selection.
def select(population, evaluation, tournamentSize):
  winner = numpy.random.randint(0, len(population))
  for i in range(tournamentSize - 1):
    rival = numpy.random.randint(0, len(population))
    if (evaluation[rival] > evaluation[winner]):
      winner = rival
  return population[winner]
# Implements a genetic algorithm for solving the max-one problem with individuals using the binary representation.
def geneticAlgorithm(n, populationSize, cRate, mRate, generations):
  # Creates the initial population (it also evaluates it)
  population = [None] * populationSize
  evaluation = [None] * populationSize
  for i in range(populationSize):
    individual = createIndividual(n)
    population[i] = individual
    evaluation[i] = evaluate(individual)
  # Keeps a record of the best individual found so far
  index = 0;
  for i in range(1, populationSize):
    if (evaluation[i] < evaluation[index]):
      index = i;
  bestIndividual = population[index]
  bestEvaluation = evaluation[index]
  # Runs the evolutionary process
  for i in range(generations):
    k = 0
    newPopulation = [None] * populationSize
    for j in range(populationSize // 2):
      parentA = select(population, evaluation, 3)
      parentB = select(population, evaluation, 3)
      newPopulation[k], newPopulation[k + 1] = combine(parentA, parentB, cRate)
      k = k + 2
    population = newPopulation
    for j in range(populationSize):
      population[j] = mutate(population[j], mRate)
      evaluation[j] = evaluate(population[j])
      # Keeps a record of the best individual found so far
      if (evaluation[j] > bestEvaluation):
        bestEvaluation = evaluation[j]
        bestIndividual = population[j]
  return bestIndividual, bestEvaluation
# solves the problem using the genetic algorithm
solution, evaluation = geneticAlgorithm(5, 200, 0.9, 0.01, 1000)
print(solution)
print(evaluation)


[ 2 14  1  2 11  3 15  3  1 10  4  3  8  1 15]
3068
